platform :ios, '13.0'
use_frameworks!

workspace 'darkvision.xcworkspace'
project 'darkvision.xcodeproj'

target 'darkvision' do
  pod 'Alamofire', '4.9.1'
  pod 'AlamofireImage', '3.6.0'
  pod 'SwiftyJSON', '5.0.0'

  pod 'RDHCollectionViewGridLayout', '1.2.5'
  pod 'TTTAttributedLabel', '2.0.0'

  pod 'SwiftMoment', '0.7'
  pod 'DateToolsSwift', '4.0.0'
  pod 'Cosmos', '20.0.1'
  pod 'TagListView', '1.4.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end
