platform :ios, '10.0'
use_frameworks!

workspace 'darkvision.xcworkspace'
xcodeproj 'darkvision.xcodeproj'

target 'darkvision' do
  pod 'Alamofire', '4.0'
  pod 'AlamofireImage', '3.0'
  pod 'SwiftyJSON', '3.0'

  pod 'RDHCollectionViewGridLayout', '1.2.5'
  pod 'TTTAttributedLabel', '2.0.0'

  pod 'SwiftMoment', :git => 'https://github.com/akosma/SwiftMoment.git', :branch => 'master'
  pod 'DateTools', :git => 'https://github.com/MatthewYork/DateTools.git', :branch => 'swift'
  pod 'Cosmos', '6.0.1'
  pod 'TagListView', :git => 'https://github.com/xhacker/TagListView.git', :branch => 'master'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
