platform :ios, '10.0'
use_frameworks!

workspace 'darkvision.xcworkspace'
project 'darkvision.xcodeproj'

target 'darkvision' do
  pod 'Alamofire', '4.2'
  pod 'AlamofireImage', '3.2'
  pod 'SwiftyJSON', '3.1.3'

  pod 'RDHCollectionViewGridLayout', '1.2.5'
  pod 'TTTAttributedLabel', '2.0.0'

  pod 'SwiftMoment', '0.7'
  pod 'DateTools', :git => 'https://github.com/MatthewYork/DateTools.git', :branch => 'swift'
  pod 'Cosmos', '7.0'
  pod 'TagListView', '1.1.0'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
